import { vi } from 'vitest'

// Mock uni-app global APIs
;(globalThis as any).uni = {
  showToast: vi.fn(),
  showModal: vi.fn(),
  showLoading: vi.fn(),
  hideLoading: vi.fn(),
  navigateTo: vi.fn(),
  redirectTo: vi.fn(),
  reLaunch: vi.fn(),
  switchTab: vi.fn(),
  navigateBack: vi.fn(),
  getStorageSync: vi.fn(),
  setStorageSync: vi.fn(),
  removeStorageSync: vi.fn(),
  getSystemInfoSync: vi.fn(() => ({
    platform: 'devtools',
    windowWidth: 375,
    windowHeight: 667,
  })),
  getAccountInfoSync: vi.fn(() => ({
    miniProgram: {
      envVersion: 'develop',
    },
  })),
  request: vi.fn(),
  uploadFile: vi.fn(),
  downloadFile: vi.fn(),
  chooseImage: vi.fn(),
  previewImage: vi.fn(),
  saveImageToPhotosAlbum: vi.fn(),
  getImageInfo: vi.fn(),
  compressImage: vi.fn(),
  getLocation: vi.fn(),
  openLocation: vi.fn(),
  chooseLocation: vi.fn(),
  scanCode: vi.fn(),
  setClipboardData: vi.fn(),
  getClipboardData: vi.fn(),
  makePhoneCall: vi.fn(),
  addPhoneContact: vi.fn(),
  showActionSheet: vi.fn(),
  login: vi.fn(),
  checkSession: vi.fn(),
  getUserInfo: vi.fn(),
  getUserProfile: vi.fn(),
  authorize: vi.fn(),
  openSetting: vi.fn(),
  getSetting: vi.fn(),
  createCanvasContext: vi.fn(),
  canvasToTempFilePath: vi.fn(),
  saveFile: vi.fn(),
  getFileInfo: vi.fn(),
  getSavedFileList: vi.fn(),
  removeSavedFile: vi.fn(),
  openDocument: vi.fn(),
  onNetworkStatusChange: vi.fn(),
  getNetworkType: vi.fn(),
  onAccelerometerChange: vi.fn(),
  startAccelerometer: vi.fn(),
  stopAccelerometer: vi.fn(),
  onCompassChange: vi.fn(),
  startCompass: vi.fn(),
  stopCompass: vi.fn(),
  onBluetoothAdapterStateChange: vi.fn(),
  startBluetoothDevicesDiscovery: vi.fn(),
  stopBluetoothDevicesDiscovery: vi.fn(),
  onBluetoothDeviceFound: vi.fn(),
  getBluetoothDevices: vi.fn(),
  getConnectedBluetoothDevices: vi.fn(),
  createBLEConnection: vi.fn(),
  closeBLEConnection: vi.fn(),
  getBLEDeviceServices: vi.fn(),
  getBLEDeviceCharacteristics: vi.fn(),
  readBLECharacteristicValue: vi.fn(),
  writeBLECharacteristicValue: vi.fn(),
  notifyBLECharacteristicValueChange: vi.fn(),
  onBLEConnectionStateChange: vi.fn(),
  onBLECharacteristicValueChange: vi.fn(),
  openBluetoothAdapter: vi.fn(),
  closeBluetoothAdapter: vi.fn(),
  getBluetoothAdapterState: vi.fn(),
  startPullDownRefresh: vi.fn(),
  stopPullDownRefresh: vi.fn(),
  pageScrollTo: vi.fn(),
  createAnimation: vi.fn(() => ({
    export: vi.fn(),
    step: vi.fn(),
    translateX: vi.fn().mockReturnThis(),
    translateY: vi.fn().mockReturnThis(),
    scale: vi.fn().mockReturnThis(),
    rotate: vi.fn().mockReturnThis(),
    opacity: vi.fn().mockReturnThis(),
    width: vi.fn().mockReturnThis(),
    height: vi.fn().mockReturnThis(),
    left: vi.fn().mockReturnThis(),
    right: vi.fn().mockReturnThis(),
    top: vi.fn().mockReturnThis(),
    bottom: vi.fn().mockReturnThis(),
    backgroundColor: vi.fn().mockReturnThis(),
    matrix: vi.fn().mockReturnThis(),
    matrix3d: vi.fn().mockReturnThis(),
    skew: vi.fn().mockReturnThis(),
    skewX: vi.fn().mockReturnThis(),
    skewY: vi.fn().mockReturnThis(),
    rotateX: vi.fn().mockReturnThis(),
    rotateY: vi.fn().mockReturnThis(),
    rotateZ: vi.fn().mockReturnThis(),
    rotate3d: vi.fn().mockReturnThis(),
    scaleX: vi.fn().mockReturnThis(),
    scaleY: vi.fn().mockReturnThis(),
    scale3d: vi.fn().mockReturnThis(),
    translate: vi.fn().mockReturnThis(),
    translate3d: vi.fn().mockReturnThis(),
  })),
  createInnerAudioContext: vi.fn(() => ({
    play: vi.fn(),
    pause: vi.fn(),
    stop: vi.fn(),
    seek: vi.fn(),
    destroy: vi.fn(),
    onCanplay: vi.fn(),
    onPlay: vi.fn(),
    onPause: vi.fn(),
    onStop: vi.fn(),
    onEnded: vi.fn(),
    onTimeUpdate: vi.fn(),
    onError: vi.fn(),
    onWaiting: vi.fn(),
    onSeeking: vi.fn(),
    onSeeked: vi.fn(),
    offCanplay: vi.fn(),
    offPlay: vi.fn(),
    offPause: vi.fn(),
    offStop: vi.fn(),
    offEnded: vi.fn(),
    offTimeUpdate: vi.fn(),
    offError: vi.fn(),
    offWaiting: vi.fn(),
    offSeeking: vi.fn(),
    offSeeked: vi.fn(),
  })),
  getRecorderManager: vi.fn(() => ({
    start: vi.fn(),
    pause: vi.fn(),
    resume: vi.fn(),
    stop: vi.fn(),
    onStart: vi.fn(),
    onPause: vi.fn(),
    onResume: vi.fn(),
    onStop: vi.fn(),
    onError: vi.fn(),
    onFrameRecorded: vi.fn(),
    onInterruptionBegin: vi.fn(),
    onInterruptionEnd: vi.fn(),
  })),
  createVideoContext: vi.fn(() => ({
    play: vi.fn(),
    pause: vi.fn(),
    stop: vi.fn(),
    seek: vi.fn(),
    sendDanmu: vi.fn(),
    playbackRate: vi.fn(),
    requestFullScreen: vi.fn(),
    exitFullScreen: vi.fn(),
    hideStatusBar: vi.fn(),
    showStatusBar: vi.fn(),
  })),
  createMapContext: vi.fn(() => ({
    getCenterLocation: vi.fn(),
    moveToLocation: vi.fn(),
    translateMarker: vi.fn(),
    includePoints: vi.fn(),
    getRegion: vi.fn(),
    getScale: vi.fn(),
  })),
  createCameraContext: vi.fn(() => ({
    takePhoto: vi.fn(),
    startRecord: vi.fn(),
    stopRecord: vi.fn(),
  })),
  createLivePlayerContext: vi.fn(() => ({
    play: vi.fn(),
    stop: vi.fn(),
    mute: vi.fn(),
    pause: vi.fn(),
    resume: vi.fn(),
    requestFullScreen: vi.fn(),
    exitFullScreen: vi.fn(),
    snapshot: vi.fn(),
  })),
  createLivePusherContext: vi.fn(() => ({
    start: vi.fn(),
    stop: vi.fn(),
    pause: vi.fn(),
    resume: vi.fn(),
    switchCamera: vi.fn(),
    snapshot: vi.fn(),
    toggleTorch: vi.fn(),
    playBGM: vi.fn(),
    stopBGM: vi.fn(),
    pauseBGM: vi.fn(),
    resumeBGM: vi.fn(),
    setBGMVolume: vi.fn(),
    startPreview: vi.fn(),
    stopPreview: vi.fn(),
  })),
  getCurrentPages: vi.fn(() => []),
}

// Mock getApp
;(globalThis as any).getApp = vi.fn(() => ({
  globalData: {},
}))

// Mock getCurrentPages for router utils
Object.defineProperty(globalThis, 'getCurrentPages', {
  value: vi.fn(() => []),
  writable: true,
})
